# Generated by Django 3.1 on 2020-08-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address_line_3',
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=63, verbose_name='Region'),
        ),
    ]
